# Generated by Django 3.1.3 on 2020-11-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
