# Generated by Django 3.1.3 on 2020-11-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201120_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(max_length=100, verbose_name='Model of device')),
                ('note', models.TextField(blank=True, verbose_name='Note field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
