# Generated by Django 3.1.3 on 2020-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_givendevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=60, unique=True, verbose_name='username'),
        ),
    ]
