# Generated by Django 3.1.3 on 2020-11-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('pub_date', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0, verbose_name='Like count')),
                ('view_count', models.IntegerField(default=0, verbose_name='View count')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
