# Generated by Django 3.1.3 on 2020-11-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Post image'),
        ),
    ]
