# Generated by Django 3.1.3 on 2020-11-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201109_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_post',
            field=models.BooleanField(default=False, verbose_name='Highlited post'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
